server:
  port: 8123
  servlet:
    context-path: /api
spring:
  application:
    name: wart-picture-backend
#    限制上传文件体积，default为1MB
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wart_picture
    username: ${wart-picture.mysql.username}
    password: ${wart-picture.mysql.password}
  config:
    import:
      - classpath:application-self.properties
  redis:
    database: 0
    host: ${wart-picture.redis.host}
    port: ${wart-picture.redis.port}
    password: ${wart-picture.redis.password}
    timeout: 5000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 逻辑删除字段名
      logic-delete-value: 1 #  逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值

knife4j:
  enable: true
  openapi:
    title: 接口文档配置
    version: v1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.wart.wartpicturebackend.controller

# 腾讯云 cos配置
cos:
  client:
    host: ${wart-picture.cos.client.host}
    secret-id: ${wart-picture.cos.client.secret.id}
    secret-key: ${wart-picture.cos.client.secret.key}
    region: ${wart-picture.cos.client.region}
    bucket: ${wart-picture.cos.client.bucket}
